
version: 1.0.0-build.{build}

image:
  - Visual Studio 2019
  - macOS
platform:
  - x64
build_script:
  - ps: ./CI/AppveyorBuild.ps1
artifacts:
  - path: '*.zip'
    name: archive
deploy:
  # https://help.appveyor.com/discussions/problems/3362-deployment-to-github
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: FBX-glTF-conv-$(APPVEYOR_REPO_TAG_NAME)
  description: 'A FBX to glTF file format converter.'
  provider: GitHub
  auth_token:
    secure: kqqOO+PbfI41hxJ1NT4tkKIaIOZZxHRJLx+yghtRMgXPFUkXArTTsQUUjXzzw2/N
  artifact: archive
  draft: true
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: true
